image: node:14.4.0
stages:
  - build
  - deploy

testbuild:
  stage: build
  script:
    - chmod a+x .config.sh
    # - ./.config.sh > src/config.js
    - npm install --registry https://registry.npm.taobao.org --no-optional
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist
  only:
    - test

pages:
  stage: deploy
  script:
    - mkdir -p ~/.ssh
    - echo "$GITLAB_DEPLOY_SSH" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - ssh -tt "$GITLAB_DEPLOY_USER"@"$GITLAB_DEPLOY_HOST" "mkdir -p /data/www/$CI_PROJECT_NAME"
    - rsync -avz dist/* "$GITLAB_DEPLOY_USER"@"$GITLAB_DEPLOY_HOST":/data/www/$CI_PROJECT_NAME
  only:
    - test

masterbuild:
  stage: build
  script:
    - chmod a+x .config.sh
    - ./.config.sh
  only:
    - master

tagbuild:
  stage: build
  script:
    - chmod a+x .config.sh
    - ./.config.sh
  only:
    - tags
